name: Publish documentation
on:
  push:
    branches:
      - main
jobs:
  pack:  # to verify the deployment originates from an appropriate source
    permissions:
      contents: write
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@census_api'
      - run: npm install
      - run: npm run build
      - name: Create docs locally in CI
        run: npm run docs:api 
      - name: Deploy docs to GH pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder the action should deploy.
          branch: gh-pages

